config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index]
  resource :user, only: [:edit, :destroy, :update] do
    collection do
      patch 'update_password'
      get :cambiar_password
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/facultad.rb
class Facultad < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :current_password, :password_confirmation)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :current_password, :password_confirmation)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :cambiar_password, :update_password, :update]
  # before_action :tipo_documento_id

  def index
    @users = User.all
    if params[:q].present?
      @users = @users.where("email ilike :q", q: "%#{params[:q]}%")
    end
  end

  def show
  @user = User.find(params[:id])
  end

  def edit
  end

  def cambiar_password
  end

  def update_password
    if @user.update_with_password(user_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
      flash[:success] ="Contraseña Actualizada"
      redirect_to "/"
    else
      flash[:alert]="Error al Actualizar"
      render "edit"
    end
  end

  def update
    if current_user.update(user_params)
      flash[:success]="Registro Actualizado"
      redirect_to edit_user_path
    else
      flash[:alert]="Error al Actualizar"
      render :edit
    end
  end

  private
  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email,
                                 :tipodocumento_id,
                                 :current_password,
                                 :password_confirmation,
                                 :password)
  end

  # def tipo_documento_id
  #     @tipo = TipoDocumento.all
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end
    def is_active_controller(controller_name, class_name = nil)
        if params[:controller] == controller_name
         class_name == nil ? "active" : class_name
        else
           nil
        end
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end

    def asset_exists?(subdirectory, filename)
      File.exists?(File.join(Rails.root, 'app', 'assets', subdirectory, filename))
    end

    def image_exists?(image)
      asset_exists?('images', image)
    end

    def javascript_exists?(script)
      extensions = %w(.coffee .erb .coffee.erb) + [""]
      extensions.inject(false) do |truth, extension|
        truth || asset_exists?('javascripts', "#{script}.js#{extension}")
      end
    end

    def stylesheet_exists?(stylesheet)
      extensions = %w(.scss .erb .scss.erb) + [""]
      extensions.inject(false) do |truth, extension|
        truth || asset_exists?('stylesheets', "#{stylesheet}.css#{extension}")
      end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1 class="text-center mov-naranja">SFT <strong>AUTONOMA</strong></h1> <hr />
<h2 class="subtitulo mov-naranja"><strong>Informacion</strong></h2>
<div class="usuario">
  <div class="informacion">
    <div class="container_details">
      <div class="info">
         <p class="details_info"><strong>Rol:</strong> <%= current_user.roles.collect(&:name).join(' , ').upcase %></p>
         <p class="details_info"><strong>Correo:</strong> <%=  current_user.email %></p>
      </div>
    </div>
  </div>
  <div class="informacion_general">
    <div class="container_box">
       <div class="box">
          <div class="title">
            <h3 class="title_box"><strong>Cursos</strong></h3>
          </div>
          <div class="description">
            <h1 class="description_box">#Cursos#</h1>
          </div>
          <div class="foot">
            <h3 class="foot_box">Universidad Autonoma del Caribe</h3>
          </div>
          <div class="ver_mas">
          </div>
       </div>
       <div class="box">
          <div class="title">
              <h3 class="title_box"><strong>Instructores</strong></h3>
          </div>
          <div class="description">
              <h1 class="description_box"><%= User.count%></h1>
          </div>
          <div class="foot">
              <h3 class="foot_box"><%=current_user.email%> </h3>
          </div>
          <div class="ver_mas">
            <a class="<%= is_active_controller('users') %>">
               <%= link_to users_path do %>
                 <i class="ver_mas_box"></i> <span data-i18n="nav.layouts">Ver más</span>
               <% end %>
            </a>
          </div>
       </div>
       <div class="box">
         <div class="title">
            <h3 class="title_box"><strong>Novedades</strong></h3>
         </div>
         <div class="description">
            <h1 class="description_box"><%= User.count%></h1>
         </div>
         <div class="foot">
            <h3 class="foot_box"><%= current_user.email %></h3>
         </div>
         <div class="ver_mas">
         </div>
       </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        SFT <strong>AUTONOMA</strong> 2020.
    </div>
    <div>
        <strong>Copyright</strong> AUTONOMA &copy; 2020-202
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <!-- <img alt="image" class="rounded-circle" src="image_path('profile_small.jpg') %>"/> -->
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="block m-t-xs font-bold"></span>
                        <span class="text-muted text-xs block"><%= current_user.email %><b class="caret"></b><br><%= current_user.roles.collect(&:name).join(' , ') %></span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                       <li><a class="dropdown-item" href=" <%= edit_user_path %>" class="btn btn-nar">Mi Perfil</a></li>
                       <li><a class="dropdown-item" href="<%= cambiar_password_user_path %>">Cambiar Contraseña</a></li>
                       <li><a class="dropdown-item" href="#">Buzón</a></li>
                       <li class="dropdown-divider"></li>
                       <li><%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class:"btn btn-nar"%></li>
                   </ul>
                </div>
                <div class="logo-element">
                    SFT+
                </div>
            </li>
            <li class="<%= is_active_controller('home') %>">
                <%= link_to root_path do %>
                <i class="fa fa-diamond"></i> <span class="nav-label" data-i18n="nav.layouts">Inicio</span>
                <% end %>
            </li>
            <li class="<%= is_active_controller('users') %>">
                <%= link_to users_path do %>
                <i class="fa fa-diamond"></i> <span class="nav-label" data-i18n="nav.layouts">Docentes</span>
                <% end %>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <!--<form role="search" class="navbar-form-custom" ">
                <div class="form-group">
                    <input type="text" placeholder="Buscar..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>-->
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li style="padding: 20px">
                <span class="m-r-sm text-muted welcome-message">Bienvenido a SFT!</span>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                </a>
                <ul class="dropdown-menu dropdown-messages dropdown-menu-right">
                    <li>
                        <div class="dropdown-messages-box">
                            <a class="dropdown-item float-left" href="#">
                                <!-- <img alt="image" class="rounded-circle" src=" image_path('a7.jpg') %>"> -->
                            </a>
                            <div class="media-body">
                                <small class="float-right">46h ago</small>
                                <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br/>
                                <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <div class="dropdown-messages-box">
                            <a class="dropdown-item float-left" href="#">
                                <!-- <img alt="image" class="rounded-circle" src="image_path('a4.jpg') %>"> -->
                            </a>
                            <div class="media-body ">
                                <small class="float-right text-navy">5h ago</small>
                                <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br/>
                                <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <div class="dropdown-messages-box">
                            <a class="dropdown-item float-left" href="#">
                                <!-- <img alt="image" class="rounded-circle" src="image_path('profile.jpg') %>"> -->
                            </a>
                            <div class="media-body ">
                                <small class="float-right">23h ago</small>
                                <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br/>
                                <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <div class="text-center link-block">
                            <a href="#" class="dropdown-item">
                                <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="#" class="dropdown-item">
                            <div>
                                <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                <span class="float-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <a href="#" class="dropdown-item">
                            <div>
                                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                <span class="float-right text-muted small">12 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <a href="#" class="dropdown-item">
                            <div>
                                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                <span class="float-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <div class="text-center link-block">
                            <a href="#" class="dropdown-item">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>
            <li>
                <%= link_to destroy_user_session_path, method: :delete, class:"btn btn-nar" do %>
                    <i class="fa fa-sign-out"></i>Cerrar sesión
                <%end%>
            </li>
        </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SFT</title>
    <%= csrf_meta_tags %>
    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag    params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css")%>
    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">
        <!-- Navigation -->
        <%= render 'layouts/navigation' %>
        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg <%= @extra_class %>">
            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar' %>
            <!-- Main view  -->
            <section class="down">
              <%= breadcrumbs display_single_fragment: true, style: :bootstrap %>
            </section>
            <%= custom_bootstrap_flash %>
            <%= yield %>
            <!-- Footer -->
            <%= render 'layouts/footer' %>
        </div>
    </div>
    <%= javascript_include_tag params[:controller] if javascript_exists?(params[:controller]) %>
    <%= yield :javascript %>
  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  </head>
  <body class="gray-bg">
    <!-- <h1 class="mov-naranja">Bienvenido a Seguimiento</h1> -->
    <div class="row">
        <div class="col-md-12">
        <!-- <div class="ibox-content"> -->
          <%=yield%>
        <!-- </div> -->
        </div>
    </div>
  </body>
</html>

app/views/users/_users.html.erb
<tr>
  <td><%= link_to user.email , user_path(user.id)%></td> 
</tr>

app/views/users/cambiar_password.html.erb
<center><h1 class="mov-naranja">CAMBIAR <strong>CONTRASEÑA</strong></h1></center>
<div class="col-md-6">
  <div class="container_session">
      <div class="session">
        <%= simple_form_for current_user, url: update_password_user_path do |f| %>
              <%= f.input :password,label: "Nueva Contraseña:",hint: "Deje los campos de contraseñas vacios si no desea actualizarla",required: false,input_html: { autocomplete: "new-password" , class: "form-control" } %>
              <%= f.input :password_confirmation,label: "Confirmar Nueva Contraseña:",required: false,input_html: { autocomplete: "new-password" , class: "form-control" } %>
              <%= f.input :current_password,label: "Contraseña Actual:", hint: "Se necesita su contraseña actual para confirmar",required: true,input_html: { autocomplete: "current-password" , class: "form-control" } %>
          <%= f.button :submit, "Actualizar datos", class: "btn btn-primary btn-lg " %> <br><br>
        <% end %>
      </div>
  </div>
</div>
<div class="col-md-6">
</div>

app/views/users/edit.html.erb
<div class="edit-users">
  <div class="container">
    <h2 class="text-center">Editar datos de <%= current_user.email%></h2> <hr />
    <div class="row">
      <div class="col-md-6">
          <%= simple_form_for current_user, url: user_path do |f| %>
            <div class="row">
              <div class="col-md-6">
                <%= f.input :email, required: true, autofocus: true, input_html: {class: "form-control"}%>
              </div>
                <div class="row">
                  <div class="col-md-4"></div>
                  <div class="col-md-4">
                    <%= f.button :submit, "Actualizar datos", class: "btn btn-primary btn-lg " %> <br><br>
                  <div class="col-md-4"></div>
                  <div class="row"></div><br><br>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
</div>

app/views/users/index.html.erb
<h1 class="text-center mov-naranja">LISTA DE <strong>Instructores</strong></h1>
<hr />
<div class="row">
  <%= form_tag(users_path, class:"navbar-form-custom" , method: :get) do %>
    <div class="form-group">
      <input type="text" name="q" class="form-control" placeholder="Buscar..." type="text" value="<%= params[:q] %>">
    </div>
  <%end%>
</div> <br>
<table class="table table-striped">
  <tr>
    <th class="active">Email</th>
  </tr>
  <%= render partial: "users", collection: @users, as: :user %>
</table>

app/views/users/show.html.erb
<h1 class="text-center mov-naranja"><strong><%=  @user.email %></strong></h1><hr />
<div class="usuario">
  <div class="informacion">
    <div class="container_details">
      <div class="info">
         <p class="details_info"><strong>Rol:</strong> <%= @user.roles.collect(&:name).join(' , ').upcase %></p>
         <p class="details_info"><strong>Correo:</strong> <%=  @user.email %></p>
      </div>
    </div>
  </div>
</div>